on:
  push:
    tags:
      - v*
name: CD release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: actions/subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
    - run: flutter pub get
    - run: flutter build apk -t lib/main_prod.dart --split-per-abi
    - name: Release apk 
      uses: ncipollo/release-action@v1
      with: 
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{secrets.YT_FLUTTER}}
        
